spring.application.name: demo
external-services:
  auth-provider:  # Auth Server ???????? Token
    base-url: http://localhost:3000
    token-path: /oauth/token
    client-id: ${AUTH_CLIENT_ID:my-client-id}
    client-secret: ${AUTH_CLIENT_SECRET:my-secret-key}
  product-api: # Business API ???????????????????
    base-url: http://localhost:3000
    get-product-path: /api/resource
